/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Pablo PC
 */
public class Bodega extends javax.swing.JDialog {

    public Bodega(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botonMercados = new javax.swing.JButton();
        botonMundos = new javax.swing.JButton();
        botonMinas = new javax.swing.JButton();
        botonConectores = new javax.swing.JButton();
        botonArmerias = new javax.swing.JButton();
        botonTemplo = new javax.swing.JButton();
        botonMisil = new javax.swing.JButton();
        botonMulti = new javax.swing.JButton();
        botonCombo = new javax.swing.JButton();
        botonBomba = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        numeroMisiles = new javax.swing.JLabel();
        numeroMulti = new javax.swing.JLabel();
        numeroBombas = new javax.swing.JLabel();
        numeroCombos = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        numeroMundos = new javax.swing.JLabel();
        numeroMercados = new javax.swing.JLabel();
        numeroConectores = new javax.swing.JLabel();
        numeroMina = new javax.swing.JLabel();
        numeroArmerias = new javax.swing.JLabel();
        numeroTemplos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        numeroNaves = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numeroEspias = new javax.swing.JLabel();
        botonEspias = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        numeroComodines = new javax.swing.JLabel();
        botonNave = new javax.swing.JButton();
        Como = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mercados:");

        jLabel2.setText("Mundos:");

        jLabel3.setText("Conectores:");

        jLabel5.setText("Armerias:");

        jLabel6.setText("Templo:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Armas");

        jLabel8.setText("Bomba:");

        jLabel9.setText("Misil:");

        jLabel10.setText("Multi-shot:");

        jLabel11.setText("Combo-shot:");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonMercados.setText("*");
        botonMercados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMercadosMouseClicked(evt);
            }
        });

        botonMundos.setText("jButton2");
        botonMundos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMundosMouseClicked(evt);
            }
        });

        botonMinas.setText("jButton2");
        botonMinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMinasMouseClicked(evt);
            }
        });

        botonConectores.setText("jButton2");
        botonConectores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConectoresMouseClicked(evt);
            }
        });

        botonArmerias.setText("jButton2");
        botonArmerias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonArmeriasMouseClicked(evt);
            }
        });

        botonTemplo.setText("jButton2");
        botonTemplo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTemploMouseClicked(evt);
            }
        });

        botonMisil.setText("jButton2");
        botonMisil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMisilMouseClicked(evt);
            }
        });

        botonMulti.setText("jButton2");
        botonMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMultiMouseClicked(evt);
            }
        });

        botonCombo.setText("jButton2");
        botonCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonComboMouseClicked(evt);
            }
        });

        botonBomba.setText("jButton2");
        botonBomba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBombaMouseClicked(evt);
            }
        });

        jLabel12.setText("Minas:");

        jLabel13.setText("Combo-shot:");

        jLabel15.setText("Comodines:");

        jLabel4.setText("Espía:");

        botonEspias.setText("Aplicar");
        botonEspias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEspiasMouseClicked(evt);
            }
        });

        jLabel16.setText("Nave:");

        botonNave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonNaveMouseEntered(evt);
            }
        });

        Como.setText("Aplicar");
        Como.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(numeroMercados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(botonMercados, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonArmerias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonMinas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonTemplo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(botonConectores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(numeroEspias, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(botonEspias)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroArmerias, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numeroMina, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numeroTemplos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numeroConectores, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroMundos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMundos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroMisiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numeroMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numeroBombas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numeroCombos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonMisil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonBomba, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numeroNaves, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numeroComodines, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Como)
                                    .addComponent(botonNave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(359, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(262, 262, 262)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(botonMercados))
                                                    .addComponent(numeroMercados, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(numeroMundos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(botonMundos)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(numeroMisiles, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(51, 51, 51)
                                                    .addComponent(jLabel9))))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel10)
                                                    .addComponent(numeroMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(botonConectores)))
                                            .addComponent(numeroConectores, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(botonMisil)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonMulti)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(botonMinas)
                                                .addComponent(numeroBombas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel12)
                                            .addComponent(numeroMina, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(numeroCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(numeroArmerias, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(botonBomba)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonCombo))))
                            .addComponent(botonArmerias))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(numeroTemplos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(Como))
                                            .addComponent(numeroComodines, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(numeroNaves, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(botonEspias)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel17))
                                                .addComponent(jLabel16)
                                                .addComponent(numeroEspias, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(botonNave, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(botonTemplo)))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(276, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(67, 67, 67)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMercadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMercadosMouseClicked
        JuegoGato.setChoosen(1);
        JuegoGato.getEnManoLabel().setText("Mercado");
    }//GEN-LAST:event_botonMercadosMouseClicked

    private void botonMundosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMundosMouseClicked
        JuegoGato.setChoosen(2);
        JuegoGato.getEnManoLabel().setText("Mundo");
    }//GEN-LAST:event_botonMundosMouseClicked

    private void botonConectoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConectoresMouseClicked
        JuegoGato.setChoosen(3);
        JuegoGato.getEnManoLabel().setText("Conector");
    }//GEN-LAST:event_botonConectoresMouseClicked

    private void botonMinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinasMouseClicked
        JuegoGato.setChoosen(5);
        JuegoGato.getEnManoLabel().setText("Mina");
    }//GEN-LAST:event_botonMinasMouseClicked

    private void botonArmeriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonArmeriasMouseClicked
        JuegoGato.setChoosen(4);
        JuegoGato.getEnManoLabel().setText("Armeria");
    }//GEN-LAST:event_botonArmeriasMouseClicked

    private void botonTemploMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTemploMouseClicked
        JuegoGato.setChoosen(6);
        JuegoGato.getEnManoLabel().setText("Templo");
    }//GEN-LAST:event_botonTemploMouseClicked

    private void botonMisilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMisilMouseClicked
        JuegoGato.setChoosen(7);
        JuegoGato.getEnManoLabel().setText("Misil");
    }//GEN-LAST:event_botonMisilMouseClicked

    private void botonMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMultiMouseClicked
        JuegoGato.setChoosen(8);
        JuegoGato.getEnManoLabel().setText("Multi-shoot");
    }//GEN-LAST:event_botonMultiMouseClicked

    private void botonBombaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBombaMouseClicked
        JuegoGato.setChoosen(9);
        JuegoGato.getEnManoLabel().setText("Bomba");
    }//GEN-LAST:event_botonBombaMouseClicked

    private void botonComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComboMouseClicked
        JuegoGato.setChoosen(10);
        JuegoGato.getEnManoLabel().setText("Combo-shoot");
    }//GEN-LAST:event_botonComboMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonEspiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEspiasMouseClicked
        JuegoGato.setChoosen(12);
        JuegoGato.espiaAux();
    }//GEN-LAST:event_botonEspiasMouseClicked

    private void botonNaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNaveMouseEntered

    private void botonNaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNaveMouseClicked
        JuegoGato.setChoosen(11);
        JuegoGato.getEnManoLabel().setText("Nave");
        
    }//GEN-LAST:event_botonNaveMouseClicked

    private void ComoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComoMouseClicked
        JuegoGato.setProteccion(true);;
    }//GEN-LAST:event_ComoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Bodega dialog = new Bodega(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Como;
    public static javax.swing.JButton botonArmerias;
    public static javax.swing.JButton botonBomba;
    public static javax.swing.JButton botonCombo;
    public static javax.swing.JButton botonConectores;
    public javax.swing.JButton botonEspias;
    public static javax.swing.JButton botonMercados;
    public static javax.swing.JButton botonMinas;
    public static javax.swing.JButton botonMisil;
    public static javax.swing.JButton botonMulti;
    public static javax.swing.JButton botonMundos;
    public javax.swing.JButton botonNave;
    public static javax.swing.JButton botonTemplo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel numeroArmerias;
    public static javax.swing.JLabel numeroBombas;
    public static javax.swing.JLabel numeroCombos;
    public javax.swing.JLabel numeroComodines;
    public static javax.swing.JLabel numeroConectores;
    public javax.swing.JLabel numeroEspias;
    public static javax.swing.JLabel numeroMercados;
    public static javax.swing.JLabel numeroMina;
    public static javax.swing.JLabel numeroMisiles;
    public static javax.swing.JLabel numeroMulti;
    public static javax.swing.JLabel numeroMundos;
    public javax.swing.JLabel numeroNaves;
    public static javax.swing.JLabel numeroTemplos;
    // End of variables declaration//GEN-END:variables

    public  JButton getBotonArmerias() {
        return botonArmerias;
    }

    public  JButton getBotonBomba() {
        return botonBomba;
    }

    public  JButton getBotonCombo() {
        return botonCombo;
    }

    public  JLabel getNumeroMinas() {
        return numeroNaves;
    }

    public  JButton getBotonConectores() {
        return botonConectores;
    }

    public JButton getBotonEspias() {
        return botonEspias;
    }

    public void setBotonEspias(JButton botonEspias) {
        this.botonEspias = botonEspias;
    }

    public JButton getBotonNave() {
        return botonNave;
    }

    public void setBotonNave(JButton botonNave) {
        this.botonNave = botonNave;
    }

   

    public  JLabel getNumeroEspias() {
        return numeroEspias;
    }

    

    public  JLabel getNumeroNaves() {
        return numeroNaves;
    }

    public void setNumeroNaves(JLabel numeroNaves) {
        numeroNaves = numeroNaves;
    }

    public  JButton getBotonMercados() {
        return botonMercados;
    }

    public  JButton getBotonMinas() {
        return botonMinas;
    }

    public  JButton getBotonMisil() {
        return botonMisil;
    }

    public  JButton getBotonMulti() {
        return botonMulti;
    }

    public  JButton getBotonMundos() {
        return botonMundos;
    }

    public  JButton getBotonTemplo() {
        return botonTemplo;
    }

    public  JLabel getNumeroArmerias() {
        return numeroArmerias;
    }

    public  JLabel getNumeroBombas() {
        return numeroBombas;
    }

    public  JLabel getNumeroCombos() {
        return numeroCombos;
    }

    public  JLabel getNumeroConectores() {
        return numeroConectores;
    }

    public  JLabel getNumeroMina() {
        return numeroMina;
    }

    public  JLabel getNumeroMercados() {
        return numeroMercados;
    }

    public  JLabel getNumeroMisiles() {
        return numeroMisiles;
    }

    public  JLabel getNumeroMulti() {
        return numeroMulti;
    }

    public  JLabel getNumeroMundos() {
        return numeroMundos;
    }

    public  JLabel getNumeroTemplos() {
        return numeroTemplos;
    }

    public JLabel getNumeroComodines() {
        return numeroComodines;
    }

    public void setNumeroComodines(JLabel numeroComodines) {
        this.numeroComodines = numeroComodines;
    }

    public JButton getComo() {
        return Como;
    }

    public void setComo(JButton Como) {
        this.Como = Como;
    }
    

}
